akhramov/org-wild-notifier.el

org-wild-notifier.el

Since package depends on org, and org is neither on Elpa nor on Melpa,
installation fails (tested on Emacs 25 fresh installation).
Instead of depending on particular org version it makes sense to
depend on an Emacs version.

[Fixes #5] Remove org dependency

---

org-wild-notifier.el
tests/org-wild-notifier-tests.el

Somehow `org-wild-notifier-check` overwrites `org-agenda-buffer-name` (durably) while doing its process. 
After that, if you create an agenda view, it will be closed by the next call to `org-wild-notifier-check`.
By adding `org-agenda-buffer-name` to the `let` statement, it is reassignated to its value at the end of `org-wild-notifier-check`.

Avoid overwritting `org-agenda-buffer-name`

---

org-wild-notifier.el
tests/fixtures/planning.org
tests/org-wild-notifier-tests.el

Follow #7 
Now classic timestamps (e.g. `<2018-02-21 Tue 20:52>`) are also watched by org-wild-notifier.

Also watch for classic timestamps

---

org-wild-notifier.el

Hi, thanks for making the nice package! I modified a line to kill the org buffers opened by the checking procedure, so we don't leave the tmp buffers in the buffer list. Could you please review and let me know what you think?

org-agenda-exit kills org buffers opened for checking

---

README.org
org-wild-notifier.el
tests/fixtures/planning.org
tests/org-wild-notifier-tests.el

Currently it's possible to whitelist and blacklist entries by their
keywords (e.g. TODO, DONE). However, it may be handy to filter entries
by tags instead.
This change implements tags-based whitelisting & blacklisting

Tags whitelisting

---

.travis.yml
org-wild-notifier.el
tests/org-wild-notifier-tests.el

[#23] If agenda files are missing for some reason, org-mode presents
user an interactive choice whether to delete those files or not. Since
we're running agenda in an async process.. Well, Emacs just hangs.
[#21] straight.el modifies load path and therefore we cannot load any
of packages in forked emacs process...
This change
* [#23] filters-out non-existent agenda files
* [#21] injects load-path variable to forked emacs env.
* Fixes build for emacs 24 & 25.

Non-existent files fix (#23) and straight.el support (#21)

---

.travis.yml
org-wild-notifier.el
tests/org-wild-notifier-tests.el

`org-wild-notifier-check` causes a lag. The issue originates in
`async` library, namely, `async-sandbox` blocking the main thread
This change
* modifies `org-wild-notifier-check` function to opt
`async-sandbox` out in favor of `async-start` + callback.
* fixes the travis build & bumps emacs CI versions

[#25] Emacs lags when check runs

---

README.org
org-wild-notifier.el
tests/org-wild-notifier-tests.el

As for now, org-wild-notifier notifies just once, if
WILD_NOTIFIER_NOTIFY_BEFORE property is not set. If user wants to be
notified of all events multiple times, they'd have to set the property
on the every single agenda entry, which is inconvenient.
This change tweaks `org-wild-notifier-alert-time` custom variable to
support array values, which effectively gives the semantic described
above.

[#32] Multiple alert times for all entries

---

org-wild-notifier.el
tests/fixtures/planning.org
tests/org-wild-notifier-tests.el

It was reported that alerts for keyword-less events won't fire even if
the keywords whitelist is nil. This happens because custom variables
overrides won't load in the async process, if variables were not set
via customize.
This change sets all relevant custom variables within the async
process context.

[#37] Events without keywords

---

org-wild-notifier.el

Dash 2.18.0 now subsumes `dash-functional`.
See https://github.com/magnars/dash.el/blob/master/NEWS.md#from-217-to-218

Replace deprecated dash-functional dependency

---

org-wild-notifier.el

The variable org-agenda-files may be set to a string, which is used as
a file name.  That file is read, and each line in the file is used as
an agenda file.

Use org-agenda-files function to read agenda files list

---

org-wild-notifier.el
tests/org-wild-notifier-tests.el

I've stumbled upon this package quite recently and this was exactly what I needed. Thanks for the nice package!
There were a few things that I thought could be improved, and showing the absolute event time in the notification (in HH:MM format) was one of them, as already pointed out in #43, so I modified the message body accordingly. Since I was making changes to the message text anyway, I included the changes in #42 too. I also made adjustments to the test cases to incorporate these changes.
Hope this helps!

Showing absolute time in message

---

README.org
org-wild-notifier.el

I suppose it is useful to have different notification icons in different Emacs apps, so I added the variable to your package.

Add variable to customize notification icon

---

org-wild-notifier.el

I introduced a bug in 68c34ae when changing the way event is checked for notification. The last check time was updated on the first event check instead of at the end of all event checks. That meant it would only properly fire notification for the first event. This commit fixes the bug by moving the last check time update to the end of the all event checks.

Fix bug in check event.

---

org-wild-notifier.el

The events are now passed around as alists and not markers, so we needed to update how we access entry properties.
This fixes #59.

Fix type error in white-/blacklist functions

---

org-wild-notifier.el

As advised at [#40](https://github.com/akhramov/org-wild-notifier.el/issues/40#issue-719845080), added `org-todo-keywords` to the variables pulled in for `org-wild-notifier--retrieve-events`. That issue [notes](https://github.com/akhramov/org-wild-notifier.el/issues/40#issuecomment-707478522) that `org-wild-notifier-alert-times-property` is also missing, but I didn't touch that; I don't use that property and am not convinced I would know whether it was working right.

Pull in org-todo-keywords when retrieving events (#40) (#55)

---

org-wild-notifier.el

By default, `async-start' will use the current buffer's default-directory as the working directory for the spawned Emacs process.  In a timer, though, the current buffer may be whatever the user happens to be looking at, and the directory may not exist (which causes annoying error messages).
Hard code the process to run in the user's HOME directory, which ought to always exist and should be portable across operating systems.

Run async process in HOME directory

---

org-wild-notifier.el

It's inconvenient to prompt the user whether they want to kill the asynchronous check process.  They almost certainly don't care if Emacs makes one last notification check, if they're already killing Emacs.  Besides, the process entry is just `emacs ... -f async-batch-invoke`, whose purpose is not super clear, so it's not obvious to the user whether it's safe to proceed.

Don't prevent the user from killing emacs while a check is running

---

org-wild-notifier.el

jwiegley/emacs-async#181 added a process filter to async.el which scans for any password prompts in the child process's output and prompts the user (used for async functions that need to authenticate over TRAMP, for example).
However, org-wild-notifier passes back an arbitrary large sexp from the child process which may accidentally match
tramp-password-prompt-regexp (in my case, the bracketed characters in "shop[pin]g list ... [:]").
To prevent this situation, disable async-prompt-for-password for processes started by org-wild-notifier.
(PR note: let-binding async-prompt-for-password doesn't work until jwiegley/emacs-async#182 is merged, but I expect that PR to be fairly uncontroversial.)

Prevent async process from prompting for passwords

---

org-wild-notifier.el

fixes error: Symbol’s function definition is void: org-duration-to-minutes

Add require org-duration and depend on emacs 26.1

---

org-wild-notifier.el

useful for specifying alert styles
```
(alert-add-rule :category "org-wild-notifier"
:style (cond (alert-libnotify-command
'libnotify)
(alert-default-style)))
```

Add category to alert

---

org-wild-notifier.el

Use async-process-noquery-on-exit to make sure stderr is also ignored
